# Generated by Django 5.1.13 on 2025-10-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_libro_biblioteca'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='autores',
            field=models.ManyToManyField(to='biblioteca.autor'),
        ),
    ]
