# Generated by Django 5.1.12 on 2025-10-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_prestamos_cliente_libros'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='libros_favoritos',
            field=models.ManyToManyField(related_name='favoritos', to='biblioteca.libro'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='libros',
            field=models.ManyToManyField(related_name='libros', through='biblioteca.Prestamos', to='biblioteca.libro'),
        ),
    ]
